from create_key_words import save_key_words_db

if __name__ == "__main__":
    models = ["mistral:7b", "gemma3:4b"]
    # Liste de vos catégories ici
    categories = [
        "gardening",
        "parenting",
        "diy_projects",
        "astrology",
        "cryptocurrency",
        "cybersecurity",
        "interior_design",
        "camping",
        "sailing",
        "knitting",
        "minimalism",
        "real_estate",
        "entrepreneurship",
        "volunteering",
        "survivalism",
        "skincare",
        "nutrition",
        "baking",
        "archaeology",
        "genealogy",
        "investing",
        "e_sports",
        "biotechnology",
        "philanthropy",
    ]
    # categories = [
    #     "politics",
    #     "happiness",
    #     "art",
    #     "health",
    #     "environment",
    #     "science",
    #     "education",
    #     "technology",
    #     "music",
    #     "literature",
    #     "sports",
    #     "food",
    #     "travel",
    #     "fashion",
    #     "history",
    #     "philosophy",
    #     "psychology",
    #     "economy",
    #     "law",
    #     "culture",
    #     "nature",
    #     "relationships",
    #     "movies",
    #     "theater",
    #     "photography",
    #     "architecture",
    #     "medicine",
    #     "space",
    #     "engineering",
    #     "climate",
    #     "animals",
    #     "plants",
    #     "energy",
    #     "transportation",
    #     "gaming",
    #     "innovation",
    #     "mindfulness",
    #     "religion",
    #     "journalism",
    #     "finance",
    #     "social_media",
    #     "activism",
    #     "comedy",
    #     "mythology",
    #     "political_theory",
    #     "ethics",
    #     "astronomy",
    #     "robotics",
    #     "environmental_policy",
    # ]

    save_key_words_db(categories=categories, n_keywords=50, models=models)
